---
title: "Join Us"
page-layout: full
sidebar: false
title-block-banner: true
---

## Graduate Students

Students interested in graduate study are encouraged to contact [Prof. Wen](/contact.qmd){target="_blank"} before applying to further inquire about the opportunities available. Please include a copy of CV, a brief description of any prior research activities (note: prior research experience is not required for admission!), and your current research and educational interests. Interested students can check this **[departmental website](https://artsandsciences.syracuse.edu/earth-sciences-department/graduate-programs-earth-sciences/application-information/){target="_blank"}** for the admission requirements.

I am currently seeking applicants for graduate student positions interested in three tracks:

**Noble gas geochemistry track**: Students will apply noble gases as a dating and tracing tool for fluid and solid samples. Students will be trained in noble gas geochemistry with respect to both laboratory and data analysis skills. Students will conduct experimental noble gas work in shallow and deep groundwater, natural gas, and/or rock samples.

**Environmental data sciences and geospatial modeling track**: Students will work on a DOE-funded project to learn and apply machine learning and geospatial modeling to analyze multidisciplinary datasets to assess environmental impacts and greenhouse gas emission of oil and gas wells.

**Global elemental and water cycles track**: Students will assess the elemental and water fluxes from the land water systems using machine learning, hydrological modeling, and/or Earth system modeling. Interested students should have a background in hydrogeology, geochemistry, or relevant fields and a motivation to learn programming.

**External Graduate Student Fellowships** I am happy to work with interested candidates to collaboratively develop proposals for external graduate student fellowships, e.g., [NSF GRFP](https://www.nsfgrfp.org){target="_blank"}.

## Undergraduate Students

Students interested in conducting research in the WEN research group should contact Prof. Wen.

## Postdoctorals and Others

### Research Scientist in Noble Gas Geochemistry Laboratory

This is a multi-year annually renewable research scientist position. The noble gas geochemistry laboratory contains two state-of-the-art noble gas mass spectrometers (a Helix SFT and an Argus VI) and two extraction/purification lines (one for fluids and one for rocks). The noble gas geochemistry laboratory will be able to analyze the full suite of noble gases in gas, water, and rock samples. The candidate will assist in the management of the noble gas geochemistry laboratory and performing noble gas geochemistry research. The candidate will conduct experimental noble gas work in shallow and deep groundwater, natural gas, and rock samples. The candidate will be expected to collaborate with faculty members in ongoing research projects with the possibility to conduct independent research. The successful candidate will also have the option to participate in teaching, including lectures and laboratory teaching of both undergraduate and graduate students.

### Postdoctoral Scholars

**Environmental data sciences and geospatial modeling track**: The postdoctoral scholar will work on a DOE-funded project to learn and apply machine learning and geospatial modeling to analyze multidisciplinary datasets to assess environmental impacts and greenhouse gas emission of oil and gas wells.

**External Postdoctoral Fellowships** I am happy to work with interested candidates to collaboratively develop proposals for external postdoctoral fellowships, e.g., [NSF EAR-PF](https://new.nsf.gov/funding/opportunities/ear-postdoctoral-fellowships-ear-pf){target="_blank"}.
