---
title: "Publication"
page-layout: full
sidebar: false
title-block-banner: true
---

You can find my publications on my [Google Scholar](https://scholar.google.com/citations?user=5jsj4tUAAAAJ){target=_blank} webpage.

## Journal Articles
† = Student author, directly supervised by Wen at time of publication

†† = Student author of collaborator(s) at time of publication

### 2024
* ††Shaheen, S., **Wen, T.**, Zheng, Z., Xue, L., Baka, J. and Brantley, S.L., 2024. Wastewaters Coproduced with Shale Gas Drive Slight Regional Salinization of Groundwater. _Environmental Science & Technology_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Shaheen_2024_EST.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1021/acs.est.4c03371){.btn .btn-sm target=_blank} 

* Hammond, P.A., **Wen, T.**, Woda, J. and Oakley, D., 2024. Pathways and environmental impacts of methane migration: case studies in the Marcellus Shale, USA. _Geofluids_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Hammond_2024_Geofluids.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1155/2024/9290873){.btn .btn-sm target=_blank}

* Liu, Y., Wang, T., **Wen, T.**, Zhang, J., Liu, B., Li, Y., Zhang, H., Rong, X., Ma, L., Guo, F., Liu, X and Sun, Y., 2024. Deep learning-based grain size decomposition model: A feasible solution for dealing with methodological uncertainty. _Sedimentology_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Liu_2024_Sedimentology.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1111/sed.13195){.btn .btn-sm target=_blank}

* †Nesheim, S., Yu, Z., Tuttle, S., †Klein, J. and **Wen, T.**, 2024. Assessing impacts of cemeteries on water quality in an urban headwater watershed with mixed human-built infrastructure. _Hydrological Processes_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Nesheim_2024_HP.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1002/hyp.15128){.btn .btn-sm target=_blank}

### 2023
* Kang, M., Boutot, J., McVay, R.C., Roberts, K., Jasechko, S., Perrone, D., **Wen, T.**, Lackey, G., Raimi, D., Digiulio D.C., Shonkoff, S.B., Carey, J.W., Elliott, E.G., Vorhees, D.J. and Peltz, A., 2023. Environmental risks and opportunities of orphaned oil and gas wells in the United States. _Environmental Research Letters_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Kang_2023_ERL.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1088/1748-9326/acdae7){.btn .btn-sm target=_blank}

* ††Shaughnessy, A.R., ††Forgeng, M.J., **Wen, T.**, Gu, X., Hemingway, J. and Brantley, S.L., Linking Stream Chemistry to Subsurface Redox Architecture. _Water Resources Research_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Shaughnessy_2023_WRR.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1029/2022WR033445){.btn .btn-sm target=_blank}

* †E, B., Zhang, S., Driscoll, C.T. and **Wen, T.**, Human and natural impacts on the U.S. freshwater salinization and alkalinization: A machine learning approach. _Science of The Total Environment_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/E_2023_STOTEN.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1016/j.scitotenv.2023.164138){.btn .btn-sm target=_blank}

* Carter, E., Hultquist, C. and **Wen, T.**, 2023. GRRIEn analysis: a data science cheat sheet for earth scientists learning from global earth observations. _Artificial Intelligence for the Earth Systems_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Carter_2023_AIES.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1175/AIES-D-22-0065.1){.btn .btn-sm target=_blank}

### 2022
* Cheng, P., Xiao, X., Ren, B., **Wen, T.** and Yu, S., 2022. Editorial: New advances in light oil/condensate geochemistry. _Frontiers in Earth Science_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Cheng_2022_FIES.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.3389/feart.2022.1079834){.btn .btn-sm target=_blank}

* †Epuna, F., ††Shaheen, S. and **Wen, T.**, 2022. Road Salting and Natural Brine Migration Revealed as Major Sources of Groundwater Contamination Across Regions of Northern Appalachia With and Without Unconventional Oil and Gas Development. _Water Research_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Epuna_et_al_2022_WR.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1016/j.watres.2022.119128){.btn .btn-sm target=_blank}

* **Wen, T.**, ††Chen, C., Zheng, G., Bandstra, J. and Brantley, S.L., 2022. Using a Neural Network – Physics-based Hybrid Model to Predict Soil Reaction Fronts. _Computers & Geosciences_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Wen_2022_CG.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1016/j.cageo.2022.105200){.btn .btn-sm target=_blank}

* ††Shaheen, S.W., **Wen, T.**, Herman, A., Brantley, S.L., 2022. Geochemical Evidence of Potential Groundwater Contamination with Human Health Risks Where Hydraulic Fracturing Overlaps with Extensive Legacy Hydrocarbon Extraction. _Environmental Science & Technology_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Shaheen_2022_EST.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1021/acs.est.2c00001){.btn .btn-sm target=_blank}

* ††Wang, S., Huang, X., **Wen, T.**, Wang, X., Wang, H., Han, Y., Li, Z., Kuang, J. and Qi S., 2022. Noble Gases in Shallow Aquifers Preserve Signatures of Boiling Events beneath Weishan Volcano of Wudalianchi Volcanic Field, Northeast China. _Journal of Hydrology_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Wang_2022_JH.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1016/j.jhydrol.2022.128246){.btn .btn-sm target=_blank}

* Boumaiza, L., Walter, J., Chesnaux, R., Stotler, R., **Wen, T.**, Johannesson K., Brindha K. and Huneau, F., 2022. Chloride-salinity as indicator of the chemical composition of groundwater: empirical predictive model based on aquifers in Southern Quebec, Canada. _Environmental Science and Pollution Research_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Boumaiza_2022_ESPR.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1007/s11356-022-19854-z){.btn .btn-sm target=_blank}

* He, Y., Zhou, Y., **Wen, T.**, Zhang, S., Huang, F., Zou, X., Ma, X., Zhu, Y., 2022. A review of machine learning in geochemistry and cosmochemistry: Method improvements and applications. _Applied Geochemistry_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/He_2022_Applied_Geochemistry.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1016/j.apgeochem.2022.105273){.btn .btn-sm target=_blank}

### 2021
* Brantley, S.L., **Wen, T.**, Agarwal, D., Catalano, J.G., Schroeder, P.A., Lehnert, K., Varadharajan, C., Pett-Ridge, J., Engle, M., Castronova, A.M., Hooper, R.P., Ma, X., Jin, L., McHenry, K., Aronson, E., Shaughnessy, A.R., Derry, L.A., Richardson, J., Bales, J., Pierce, E.M., 2021. The future low-temperature geochemical data-scape as envisioned by the U.S. geochemical community. _Computers & Geosciences_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Brantley_2021_CG.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1016/j.cageo.2021.104933){.btn .btn-sm target=_blank}

* Liu, R., **Wen, T.**, Amalberti, J., Zheng, J., Hao, F. and Jiang D., 2021. The Dichotomy in Noble Gas Signatures Linked to Tectonic Deformation in Wufeng-Longmaxi Shale, Sichuan Basin. _Chemical Geology_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Liu_2021_Chemical_Geology.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1016/j.chemgeo.2021.120412){.btn .btn-sm target=_blank}

* Zheng, G., Liu, C., Wei, H., Jenkins, P., Chen, C., **Wen, T.** and Li, Z., 2021. Knowledge-based Residual Learning. In _Proceedings of the 30th International Joint Conference on Artificial Intelligence_ (IJCAI 2021).<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Zheng_2021_IJCAI.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.24963/ijcai.2021/228){.btn .btn-sm target=_blank}

* **Wen, T.**, Liu, M., Woda, J., Zheng, G. and Brantley, S.L., 2021. Detecting anomalous methane in groundwater within hydrocarbon production areas across the United States. _Water Research_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Wen_2021_WR.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1016/j.watres.2021.117236){.btn .btn-sm target=_blank}

* ††Shaughnessy, A., Gu, X., **Wen, T.** and Brantley, S.L., 2021. Machine Learning Deciphers CO2 Sequestration and Subsurface Flowpaths from Stream Chemistry. _Hydrology and Earth System Sciences_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Shaughnessy_2021_HESS.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.5194/hess-25-3397-2021){.btn .btn-sm target=_blank}

* Niu, X., **Wen, T.** and Brantley, S.L., 2021. Exploring the trend of stream sulfate concentrations as U.S. power plants shift from coal to shale gas. _Environmental Pollution_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Niu_2021_Environmental_Pollution.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1016/j.envpol.2021.117102){.btn .btn-sm target=_blank}

### Prior to 2021
* ††Agarwal, A., **Wen, T.**, ††Chen, A., ††Zhang, A.Y., Niu, X., Zhan, X., Xue, L., Brantley, S.L., 2020. Assessing Contamination of Stream Networks Near Shale Gas Development Using a New Geospatial Tool. _Environmental Science & Technology_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Agarwal_Wen_2020_EST.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1021/acs.est.9b06761){.btn .btn-sm target=_blank}

* ††Woda, J., **Wen, T.**, Lemon, J., ††Marcon, V., Keeports, C.M., Zelt, F., Steffy, L.Y. and Brantley, S.L., 2020. Methane concentrations in streams reveal gas leak discharges in regions of oil, gas, and coal development. _Science of The Total Environment_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Woda_2020_STOTEN.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1016/j.scitotenv.2020.140105){.btn .btn-sm target=_blank}

* Hammond, P.A., **Wen, T.**, Brantley, S.L. and Engelder, T., 2020. Gas well integrity and methane migration: evaluation of published evidence during shale-gas development in the USA. _Hydrogeology Journal_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Hammond_2020_Hydrogeology.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1007/s10040-020-02116-y){.btn .btn-sm target=_blank}

* ††Shaughnessy, A., **Wen, T.**, Niu, X. and Brantley, S.L., 2019. Three Principles to Use in Streamlining Water Quality Research through Data Uniformity. _Environmental Science & Technology_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Shaughnessy_2019_EST.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1021/acs.est.9b06406){.btn .btn-sm target=_blank}

* **Wen, T.**, ††Woda, J., ††Marcon, V., Niu, X., Li, Z. and Brantley, S.L., 2019. Exploring How to Use Groundwater Chemistry to Identify Migration of Methane near Shale Gas Wells in the Appalachian Basin. _Environmental Science & Technology_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Wen_2019_EST.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1021/acs.est.9b02290){.btn .btn-sm target=_blank}

* Liu, R., Heinemann, N., Liu, J., Zhu, W., Wilkinson, M., Xie, Y., Wang, Z., **Wen, T.**, Hao, F., Haszeldine, S.R., 2019. CO2 Sequestration by Mineral Trapping in Natural Analogues in the Yinggehai Basin, South China Sea. _Marine and Petroleum Geology_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Liu_2019_MPG.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1016/j.marpetgeo.2019.03.018){.btn .btn-sm target=_blank}

* **Wen, T.**, ††Agarwal, A., Xue, L., ††Chen, A., Herman, A., Li, Z. and Brantley, S.L., 2019. Assessing Changes in Groundwater Chemistry in Landscapes with More than 100 Years of Oil and Gas Development. _Environmental Science: Processes & Impacts_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Wen_2019_ESPI.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1039/C8EM00385H){.btn .btn-sm target=_blank}

* ††Woda, J., **Wen, T.**, ††Oakley, D., Yoxtheimer, D., Engelder, T., Castro, M.C. and Brantley, S.L., 2018. Detecting and Explaining Why Aquifers Occasionally Become Degraded Near Hydraulically Fractured Shale Gas Wells. _Proceedings of the National Academy of Sciences_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Woda_2018_PNAS.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1073/pnas.1809013115){.btn .btn-sm target=_blank}

* Larson, T.E., Nicot, J.P., Mickler, P., Castro, M.C., Darvari, R., **Wen, T.** and Hall, C.M., 2018. Monitoring Stray Natural Gas in Groundwater with Dissolved Nitrogen. An Example from Parker County, Texas. _Water Resources Research_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Larson_2018_WRR.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1029/2018WR022612){.btn .btn-sm target=_blank}

* **Wen, T.**, Niu, X., Gonzales, M., ††Zheng, G., Li, Z. and Brantley, S.L., 2018. Big groundwater data sets reveal possible rare contamination amid otherwise improved water quality for some analytes in a region of Marcellus Shale development. _Environmental Science & Technology_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Wen_2018_EST.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1021/acs.est.8b01123){.btn .btn-sm target=_blank}

* Niu, X., **Wen, T.**, Li, Z. and Brantley, S.L., 2018. One Step toward Developing Knowledge from Numbers in Regional Analysis of Water Quality. _Environmental Science & Technology_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Niu_2018_EST.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1021/acs.est.8b01035){.btn .btn-sm target=_blank}

* **Wen, T.**, Pinti, D.L., Castro, M.C., López-Hernández, A., Hall, C.M., Shouakar-Stash, O. and Sandoval-Medina, F., 2018. A Noble Gas and <sup>87</sup>Sr/<sup>86</sup>Sr Study in Fluids of the Los Azufres Geothermal Field, Mexico – Assessing Impact of Exploitation and Constraining Heat Sources. _Chemical Geology_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Wen_2018_Chemical_Geology.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1016/j.chemgeo.2018.03.010){.btn .btn-sm target=_blank}

* Brantley, S.L., Vidic, R.D., Brasier, K., Yoxtheimer, D., Pollak, J., Wilderman, C. and **Wen, T.**, 2018. Engaging over data on fracking and water quality. _Science_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Brantley_2018_Science.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1126/science.aan6520){.btn .btn-sm target=_blank}

* **Wen, T.**, Castro, M.C., Nicot, J.P., Hall, C.M., Pinti, D.L., Mickler, P., Darvari, R. and Larson, T., 2017. Characterizing the noble gas isotopic composition of the Barnett Shale and Strawn group and constraining the source of stray gas in the Trinity Aquifer, north-central Texas. _Environmental Science & Technology_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Wen_2017_EST.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1021/acs.est.6b06447){.btn .btn-sm target=_blank}

* **Wen, T.**, Castro, M.C., Nicot, J.P., Hall, C.M., Larson, T., Mickler, P. and Darvari, R., 2016. Methane Sources and Migration Mechanisms in Shallow Groundwaters in Parker and Hood Counties, Texas - A Heavy Noble Gas Analysis. _Environmental Science & Technology_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Wen_2016_EST.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1021/acs.est.6b01494){.btn .btn-sm target=_blank}

* **Wen, T.**, Castro, M.C., Ellis, B.R., Hall, C.M. and Lohmann, K.C., 2015. Assessing compositional variability and migration of natural gas in the Antrim Shale in the Michigan Basin using noble gas geochemistry. _Chemical Geology_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Wen_2015_Chemical_Geology.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1016/j.chemgeo.2015.10.029){.btn .btn-sm target=_blank}

* **Wen, T.**, Castro, M.C., Hall, C.M., Pinti, D.L. and Lohmann, K.C., 2015. Constraining groundwater flow in the Glacial Drift and Saginaw aquifers in the Michigan Basin through helium concentrations and isotopic ratios. _Geofluids_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Wen_2015_Geofluids.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1111/gfl.12133){.btn .btn-sm target=_blank}

* Boucher, C., Pinti, D.L., Roy, M., Castro, M.C., Cloutier, V., Blanchette, D., Larocque, M., Hall, C.M., **Wen, T.** and Sano, Y., 2015. Groundwater age investigation of eskers in the Amos region, Quebec, Canada. _Journal of Hydrology_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Boucher_2015_Journal_of_Hydrology.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1016/j.jhydrol.2015.01.072){.btn .btn-sm target=_blank}

* Nie, Y., Liu, X., **Wen, T.**, Sun, L. and Emslie, S.D., 2014. Environmental implication of nitrogen isotopic composition in ornithogenic sediments from the Ross Sea region, East Antarctica: Δ<sup>15</sup>N as a new proxy for avian influence. _Chemical Geology_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Nie_2014_Chemical_Geology.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1016/j.chemgeo.2013.10.031){.btn .btn-sm target=_blank}

## Chapters in Books

* **Wen, T.**, 2021. Data Mining. In: Daya Sagar, B.S., Cheng, Q., McKinley, J., Agterberg, F. (eds) Encyclopedia of Mathematical Geosciences. Springer, Cham, Switzerland. 4pp.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Wen_2021_Data_Mining.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.1007/978-3-030-26050-7_77-1){.btn .btn-sm target=_blank}

* **Wen, T.**, 2020. Data Sharing. In: Schintler L., McNeely C. (eds) Encyclopedia of Big Data. Springer, Cham, Switzerland. 3pp.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Wen_2020_Data_Sharing.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](http://doi.org/10.1007/978-3-319-32001-4_322-1){.btn .btn-sm target=_blank}

* **Wen, T.**, 2020. Data Aggregation. In: Schintler L., McNeely C. (eds) Encyclopedia of Big Data. Springer, Cham, Switzerland. 4pp.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Wen_2020_Data_Aggregation.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](http://doi.org/10.1007/978-3-319-32001-4_296-1){.btn .btn-sm target=_blank}

## Reports and Theses

* **Wen, T.**, 2017. _Development of Noble Gas Techniques to Fingerprint Shale Gas and to Trace Sources of Hydrocarbons in Groundwater_ (Doctoral dissertation, University of Michigan).<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Wen_2017_Doctoral_Dissertation.pdf){.btn .btn-sm target=_blank}
[{{< iconify mdi:university >}} URL](https://deepblue.lib.umich.edu/handle/2027.42/137063){.btn .btn-sm target=_blank}

* Nicot, JP., et al., 2015. _Understanding and Managing Environmental Roadblocks to Shale Gas Development: An Analysis of Shallow Gas, NORM, and Trace Metals_ (Technical Report, http://www.rpsea.org/projects/11122-56/).

* **Wen, T.**, 2014. _Constraining groundwater flow in the Glacial Drift and Saginaw Aquifers in the Michigan Basin through helium concentrations and isotopic ratios_ (Master thesis, University of Michigan).

* **Wen, T.**, 2011. _Analysis on nitrogen species and isotopic composition of the ornithogenic sediments from Cape Bird, Ross Island, East Antarctica_ (Bachelor thesis, University of Science and Technology of China).

## Preprints and Postprints

* Agarwal, A., **Wen, T.**, Chen, A., Zhang, A.Y., Niu, X., Zhan, X., Xue, L., Brantley, S.L., 2020. Assessing Contamination of Stream Networks Near Shale Gas Development Using a New Geospatial Tool. _EarthArXiv_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Agarwal_Wen_2020_EarthArXiv.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.31223/osf.io/qka7d){.btn .btn-sm target=_blank}

* Woda, J., **Wen, T.**, Lemon, J., Marcon, V., Keeports, C.M., Zelt, F., Steffy, L.Y. and Brantley, S.L., 2020. Methane concentrations in streams reveal gas leak discharges in regions of oil, gas, and coal development. _EarthArXiv_.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Woda_2020_EarthArXiv.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.31223/osf.io/qka7d){.btn .btn-sm target=_blank}

* Zheng, G., Liu, M., **Wen, T.**, Wang, H., Yao, H., Brantley, S.L. and Li, Z., 2019. Targeted Source Detection for Environmental Data. arXiv preprint arXiv:1908.11056.<BR>
[{{< iconify bi:file-earmark-pdf-fill >}} PDF](/files/papers/Zheng_2019_arXiv.pdf){.btn .btn-sm target=_blank}
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.48550/arXiv.1908.11056){.btn .btn-sm target=_blank}

## Open Access Datasets

* **Wen, T.**, Woda, J., Marcon, V., Gonzales, M., Niu, X., Herman, A., Guarnieri, M., Li, Z., Brantley, S.L., 2019. Shale Network – Statewide Groundwater in Pennsylvania as of January 2019, Data Commons, Penn State University.<BR>
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.26208/8ag3-b743){.btn .btn-sm target=_blank}

* **Wen, T.**, Gonzales, M., Niu, X., Herman, A., Guarnieri, M., Li, Z., Brantley, S.L., 2018. Shale Network – Mercer County Groundwater as of August 2018, Data Commons, Penn State University.<BR>
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.18113/D3967X){.btn .btn-sm target=_blank}

* **Wen, T.**, Woda, J., Gonzales, M., Herman, A., Brantley, S.L., 2018. Shale Network – Lycoming County Groundwater as of October 2018, Data Commons, Penn State University.<BR>
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.18113/D35M2X){.btn .btn-sm target=_blank}

* **Wen, T.**, Gonzales, M., Niu, X., Herman, A., Guarnieri, M., Li, Z., Brantley, S.L., 2018. Shale Network – Bradford County Groundwater as of May 2018, Data Commons, Penn State University.<BR>
[{{< iconify academicons:doi-square >}} DOI](https://doi.org/10.26208/rj0h-qf52){.btn .btn-sm target=_blank}
