---
title: "History"
subtitle: "A Network of Energy-Water Researchers"
page-layout: full
sidebar: false
toc: false
title-block-banner: true
---

## Founding the Shale Network

The Shale Network is a project funded by the National Science Foundation to help scientists and citizens publish data about water resources that may be affected by gas exploitation in shale. **Started in October 2011**, the project was initiated by scientists from Penn State, the University of Pittsburgh, Dickinson College, and throughout Pennsylvania. Our goal is to find, organize, and upload data for water resources for online publication. Your data can help. To learn more about the Shale Network and how you can help, contact us by emailing [Dr. Tao Wen](mailto:twen08@syr.edu).

The Shale Network is a group of individuals working together to organize water quality and quantity data in regions where shale gas is being exploited. The Steering Committee of the Shale Network derive from Dickinson College, the University of Pittsburgh, Penn State, and the Consortium of Universities for the Advancement of Hydrologic Sciences, Inc. (CUAHSI). The group was funded by the National Science Foundation in October 2011 to put together the database and to run annual workshops between 2012 and 2016.

The Shale Network database connects researchers, agencies, industry representatives, and community organizers to generate societally-relevant knowledge from data collected by diverse groups of scientists and citizens. The Shale Network acts as an honest broker that collates datasets and learns and teaches how to synthesize that data into useful knowledge.

## Founding Team

**Penn State Team**

The Penn State team is leading the effort for database development for waters from the central and eastern parts of PA and the Devonian shale gas region. The team will work closely with a professor at Lock Haven University, M. Khalequzzaman, who is already sampling rivers in central PA near Lock Haven.

The Director of the Shale Network is Susan Brantley, an aqueous geochemist and Director of Penn State’s Earth and Environmental Systems Institute (EESI). Brantley has more than 25 years of research experience and 10 years experience in administration of research and education teams. Brantley is responsible for coordinating and supervising all activities of the Shale Network, including the running of the annual workshops, and supervision of all Penn State personnel working on the ShaleNetwork. In this endeavor she is aided by EESI staff assistant Shelly Farrell and science writer Matt Carroll. Ferrell is the main staff coordinator for the annual workshop. Data specialists are working with Brantley to input data into the database.

David Yoxtheimer, an outreach specialist for the Penn State Marcellus Center for Outreach and Research (a center within EESI) and a PSU-trained hydrogeologist, is helping to identify and communicate with water sampling groups throughout the state. Yoxtheimer participates as part of his job in the Marcellus Center for Outreach and Education in more than 200 outreach activities per year working with PA citizens to understand Marcellus impacts.  

In addition, Yoxtheimer works closely with the Marcellus Shale Coalition (MSC), an organization committed to the responsible development of natural gas from the Marcellus Shale geological formation and the enhancement of the region’s economy related to this energy source.  The members of the coalition, which include most of the energy companies developing shale gas in both Pennsylvania and surrounding states, work with partners across the region to address issues with regulators, local, county, state and federal government officials and communities about all aspects of natural gas from the Marcellus Shale. This contact is keeping communication open with industry stakeholders and will facilitate possible future use of proprietary industry data. Conversations about proprietary data sources are already ongoing.

Dr. Greg O'Toole is a faculty member and Web technology expert at Penn State (IST, EESI), and is the ShaleNetwork HCI engineer for online networking and environmental data-sharing web applications. Greg is a Lecturer in the College of Information Science & Technology at Penn State. Greg runs the scientific content management system czen.org, a clearinghouse for research and researchers on soils and water, and he is building and managing the scientific content management system for the ShaleNetwork (shalenetwork.org). 

Jennifer Williams, Penn State researcher, works in data organization for Shale Network and also works to lead the Teen Shale Network. Teen Shale Network is an effort to help teenagers from State College Area High school and a few other high schools in the northeast to sample and analyze water quality data in the area of shale gas development.
 
**Pitt Team**

Pitt is facilitating identification and communication with water sampling groups in the western part of PA and the Devonian shale gas region and will host one of the annual ShaleNetwork meetings. Specific questions of interest to the Pitt team have included the following:

How do the flow hydrodynamics modulate the mixing processes of contaminants throughout the streams and are they important for developing appropriate protocols for water chemistry sampling? Are the above protocols similar for small streams (e.g. Fonner Run and Bates Fork) and large river systems (e.g. Monongahela River)? What are temporal and spatial scales for the mixing processes for different contaminant species? What relationships can be observed between hydrogeochemical and hydrological observations and locations of Marcellus shale extraction points as well as population density or land use characteristics?

ShaleNetwork Steering Committee member, Radisav Vidic (Environmental Engineering program in Pitt CEE with specialties in water quality, pollutant transformation, transport and water treatment), has worked since 2007 on Marcellus water quality problems.  Vidic works closely with the entire ShaleNetwork team in all aspects of management of the ShaleNetwork.

**CUAHSI Team**

Consortium of Universities for the Advancement of Hydrologic Sciences, Inc. (CUAHSI), an NSF-funded organization of academic hydrologists, is responsible for all technical aspects of the water database development and coordination with the CUAHSI-developed Hydrologic Information System. CUAHSI is providing training for ShaleNetwork personnel. CUAHSI is hosting a Hydroserver for the ShaleNetwork database. In addition, CUAHSI is assisting to adapt the HydroDesktop client for use by the ShaleNetwork team, shale gas play scientists, and citizen scientists. CUAHSI will also be providing training at the annual meetings on data access and analysis. CUAHSI will also be providing training at the annual meetings on data access and analysis. Liza Brazil, community support specialist at CUAHSI, works closely to train Penn State and Pitt personnel to input data into the HIS system.