---
title: "2018 Shale Network Workshop"
date: "May 17, 2018"
categories: [Workshop, Citizen Science, Community Engagement]
authors: 
  - name: Shale Network Team
---

**Integrating data about shale gas development: Toward a more collaborative future**

The Shale Network held its seventh annual workshop May 17 and 18 at the Penn State University Park campus and in State College, Pa. The workshop was our largest yet, drawing a diverse group interested in water quality around the Marcellus Shale drilling region in Pennsylvania.

About 120 people attended all or parts of the workshop, which included a field trip and mock spill demonstration and computer module Thursday, May 17, and a poster session and presentations and discussions throughout the day Friday, May 18.

Citizen scientists, local high school students and teachers, academics, government employees, energy industry representatives and members of watershed groups all attended and interacted during the two-day event.

Of the 118 participants: 54 were from academia, including representatives from Penn State, Pitt, Syracuse, Cincinnati, Yale, Cornell, Colorado Boulder, Binghamton, Kutztown, Indiana University of Pennsylvania and the University of Rochester; 18 were from government agencies, including the U.S. Geological Survey, the Pa. Department of Conservation and Natural Resources, the Pa. Department of Environmental Protection, the Pa. Department of Health and the Ohio Department of Natural Resources; 14 from environmental/nonprofit grounds, including the Evergreen Conservancy, the Environmental Defense Fund, FracTracker Alliance, Trout Unlimited, the Health Effects Institute and the Pa Senior Environmental Corps; and 14 from industry/consulting groups, including Shell Oil, Chevron, Chesapeake Energy and Repsol Oil and Gas.

We appreciated everyone’s contributions, and are thankful for another great workshop.

**Presentations**

[Characterization,potential toxicity, and fate of O&G wastewaters spread on roads in Pennsylvania](2018-shale-network-workshop/4_Shale_network_2018.pdf) (Travis Tasker)

[Mining Oil and Gas Well Integrity Data in Colorado and New Mexico](2018-shale-network-workshop/Lackey_2018_SGN.pdf) (Greg Lackey)

[The World of "Beneficial Reuse": Regulating the Spread of Oil and Gas Wastewater on Roads](2018-shale-network-workshop/Fowler_Regulating_Beneficial_Reuse.pdf) (Lara Fowler)

[Sociodemographic Predictors of Hydraulic Fracturing Wastewater Well Siting in Ohio](2018-shale-network-workshop/Shale_Network_Presentation_EnvJustice_2018.pdf) (Genevieve Silva, Joshua Warren, Nicole C. Deziel)

**Date(s):** May 17 and 18, 2018

**Location:** Atherton Hotel, State College, Pa., and Penn State, University Park campus

**About the Workshop**

The workshop provides an opportunity for nonscientists, researchers, experts, government officials, and members of the gas and environmental industries to compare lessons learned about water issues within the northeastern region of shale gas development. Participants take part in sharing and interpreting water data related to shale gas development.

The Shale Network is a collaborative effort between Penn State, the University of Pittsburgh and the Consortium of Universities for the Advancement of Hydrologic Sciences Inc. (CUAHSI) to collect and analyze data on water quality in the Marcellus Shale drilling region. The Pennsylvania Department of Environmental Protection participates in organizing parts of the workshop. Oak Ridge Associated Universities (ORAU) also provides funding.

The workshop steering committee for 2018 includes Susan Brantley, Dave Yoxtheimer and Matt Carroll (Penn State), Radisav Vidic (Pitt), Bob Hendricks (Shell), Liza Brazil (CUASHI), and Cindy Rogers (Evergreen Conservancy). 

**Agenda**

[Click here for the 2018 Shale Network agenda](2018-shale-network-workshop/2018_Shale_Network_Workshop_Agenda.pdf)  

**2018 Workshop Registration**

Registration is closed 

**Continuing Professional Education**

Attendees can receive: 

-   Professional Development Hours for professional engineers, land surveyors and geologists