---
title: "2019 Shale Network Workshop"
date: "May 16, 2019"
categories: [Workshop, Citizen Science, Community Engagement]
authors: 
  - name: Shale Network Team
---

**Monitoring Communities and Their Environment**

The Shale Network will hold its eighth annual workshop at the Nittany Lion Inn in State College, Pa. 

**Dates:**

May 16-17

**Location:**

The Nittany Lion Inn

**About the Workshop**

The workshop provides an opportunity for citizen scientists, researchers, government officials, energy company representatives, and environmental professionals to compare lessons learned about water and environmental issues within areas where shale energy development is occurring.

The 2019 workshop features a field trip to two shale energy-related sites that manage solid and liquid wastes derived from well drilling and oil and gas production. The first is a tour of the Eureka Resources Williamsport, Pa. facility, an oil and gas wastewater management plant. This facility is designed for the pretreatment, recycling and disposal of wastewater from natural gas drilling and production operations in the Marcellus and Utica Shales. The second is a tour of the Wayne Township Landfill in Clinton County, Pa. The landfill manages drilling cuttings and muds generated primarily from shale well drilling operations and uses some novel practices to minimize the industry’s environmental footprint. In addition, the facility hosts a compressed natural gas filling station for vehicles, including trash hauling vehicles. The tentative field trip schedule is as follows:

<table><tbody><tr><td><p>9:30 a.m.</p></td><td><p>Meet in Nittany Lion Inn lobby</p></td></tr><tr><td><p>9:45 a.m.</p></td><td><p>Depart for Williamsport</p></td></tr><tr><td><p>11:00 a.m. - 12:00 p.m.</p></td><td><p>Tour Eureka Resources gas well wastewater treatment facility</p></td></tr><tr><td><p>12:00 p.m. - 1:00 p.m.</p></td><td><p>Bring your own lunch</p></td></tr><tr><td><p>1:00 p.m.</p></td><td><p>Depart for Wayne Township</p></td></tr><tr><td><p>1:30 - 3:30 p.m.</p></td><td><p>Tour Wayne Township Landfill</p></td></tr><tr><td><p>4:30 p.m.</p></td><td><p>Return to Nittany Lion Inn</p></td></tr></tbody></table>

The Shale Network is a collaborative effort between Penn State, the University of Pittsburgh and the Consortium of Universities for the Advancement of Hydrologic Sciences Inc. (CUAHSI) to collect and analyze data on water quality in the Marcellus Shale drilling region. The Pennsylvania Department of Environmental Protection participates in organizing parts of the workshop. Oak Ridge Associated Universities (ORAU) also provides funding.

**Agenda**

[Click here for the 2019 Shale Network agenda](2019-shale-network-workshop/Agenda.pdf)  

**Continuing Professional Education**

Attendees can receive: 

-   Professional Development Hours for professional engineers, land surveyors and geologists