---
title: "2021 Shale Network Workshop"
date: "May 13, 2021"
categories: [Workshop, Citizen Science, Community Engagement]
authors: 
  - name: Shale Network Team
---

Registration for the ninth annual Shale Network Workshop is now open. The theme of the 2021 workshop is “Shale Gas: Future and Developing Issues” and includes presentations on the health effects related to shale gas development by Donna Vorhees, director of energy research at the Health Effects Institute, and Joan Casey, assistant professor of environmental health sciences at Columbia University. The workshop will be held virtually on May 13-14.

The workshop provides an opportunity for citizen scientists, researchers, government officials, energy company representatives, and environmental professionals to compare lessons learned about water and environmental issues within areas where shale energy development is occurring.

The 2021 workshop features two **virtual** field trips - one to a shale gas development site and the other to a solar farm. Workshop participants may attend both field trips; advanced registration is required.

**This year's virtual talks will not be recorded, but if speakers wish to share their slides, Shale Network will make the presentations available after the workshop.**

Shale Network is a collaborative effort between Penn State, Syracuse University, and the University of Pittsburgh to collect and analyze data on water quality in the Marcellus Shale drilling region. The Pennsylvania Department of Environmental Protection participates in organizing parts of the workshop.

[**Zoom Instructions for Participants**](2021-shale-network-workshop/How_to_Zoom-Participants-final.pdf)

[**Zoom Instructions for Panelists and Speakers**](2021-shale-network-workshop/How_to_Zoom-Panelists_and_Speakers.pdf) 

**2021 Shale Network Workshop Agenda**

[2021 Shale Network Workshop Agenda PDF](2021-shale-network-workshop/2021_Shale_Network_Workshop_Agenda.pdf)

**Workshop Organized and/or Sponsored By:** _National Science Foundation, Penn State (Earth and Environmental Systems Institute, Marcellus Center for Outreach and Research, Institutes for Energy and the Environment), University of Pittsburgh, Syracuse University, Evergreen Conservancy, Pennsylvania Department of Environmental Protection (PA DEP), Pennsylvania Department of Health_

[View the 2021 Shale Network Workshop Abstracts](2021-shale-network-workshop/2021_Abstracts.pdf)

[Watch the pre-recorded talks](https://www.youtube.com/watch?v=pdSK37cjHIY&list=PLVEuDVfB7mM5iF6YgSQeWVyBQLIcUjk4D){target="_blank"}

**Continuing professional education**

Attendees can receive:

-   Professional Development Hours for professional engineers, land surveyors, and geologists.